[default]
src = 'src'
out = 'out'
libs = ['lib']

# The address of `msg.sender` in tests
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
